### PR TITLE
Added AWS RDS, backend seems to be working

### PR DESCRIPTION
**Pull request by MattKersey**

### CODE REVIEW

**Comment by MattKersey** [comment]
Need to update build.yml file to accommodate RDS connection

**Comment by ceguiluzrosas** [comment]
> Need to update build.yml file to accommodate RDS connection

Remember that GitHub Actions YAML file that I had uploaded at the beginning of this project? It creates a DB server from a Postgres image in a container. This may be a good way alternative that doesn't require us to create a "stage" dB server on AWS. Let me know what you think! @MattKersey

**Comment by ceguiluzrosas** [comment]
Copy pasting from slack 

-------

Needs some editing but here’s the gist of it:
name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: psycopg2 prerequisites
      run: |
        sudo apt-get install python-dev libpq-dev
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests and Generate Coverage Report
      run: |
        export ENVIRONMENT="staging"
        make app-migrations 
        make migrate
        make fixtures
        pip install pytest pytest-cov pytest-django
        pytest -v --cov=./app/ --cov-report=xml
        # - name: Codecov
    - name: Code Coverage Report
      uses: codecov/codecov-action@v1.0.14
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: SEAS_OUTREACH_APP
        file: ./coverage.xml
        fail_ci_if_error: false
        verbose: true
    - name: Black Code Formatter
      uses: lgeiger/black-action@master
      with:
        args: "*/*.py --check"

**Comment by MattKersey** [comment]
@ceguiluzrosas That sounds great to me! I noticed the Postgres stuff in there yesterday but wasn't sure if it would need to be changed. Just to confirm - is the plan still to use RDS to replace the sqlite database that we have now or to just leave it as is?

**Comment by ceguiluzrosas** [comment]
Hmmm good question. I think this sounds like a group decision, maybe something we DM Rennah. I'm on the fence with this question. 

If setting up the RDS connection doesn't take that much time and we're ok with only running the RDS during demo time to reduce costs, then we should go forward with it. An additional benefit is that we can tell the class that we setup a prod RDS using industry platform (I.e. AWS). 

However, we can also just stick with the sqlite file (provided the auto-pk situation occurs with that db). It's straightforward and I don't think the TAs would mind as this isn't a cloud computing course. 

What do y'all think?

@jkim10 @yiqiao-liu @MattKersey

**Comment by yiqiao-liu** [comment]
> Hmmm good question. I think this sounds like a group decision, maybe something we DM Rennah. I'm on the fence with this question.
> 
> If setting up the RDS connection doesn't take that much time and we're ok with only running the RDS during demo time to reduce costs, then we should go forward with it. An additional benefit is that we can tell the class that we setup a prod RDS using industry platform (I.e. AWS).
> 
> However, we can also just stick with the sqlite file (provided the auto-pk situation occurs with that db). It's straightforward and I don't think the TAs would mind as this isn't a cloud computing course.
> 
> What do y'all think?
> 
> @jkim10 @yiqiao-liu @MattKersey

I'm not sure either... I agree that we should ask Rennah on this

**Comment by MattKersey** [comment]
Rennah said that RDS is not required.

**Pull request closed without merging**
