### PR TITLE
Some tweaks to History and some Charts (lol)

### PR DESCRIPTION
**Pull request by jkim10**

### CODE REVIEW

**Comment by ceguiluzrosas** [comment]
Looks good so far! @jkim10 Small notes:

1. What does the x-axis represent and what is the label hidden behind the $80? 
2. What do you envision the graph displaying? Does this graph work well when there are more than 10 items? If not, should we consider a [treemap](https://www.d3-graph-gallery.com/treemap.html)?
Screen Shot 2020-12-07 at 11 54 37 PM

4. Any chance you can add a button that redirects to the history page?
3. For some reason, my new item didn't have a checkout button.
Screen Shot 2020-12-07 at 11 55 01 PM

**Comment by jkim10** [comment]
> Looks good so far! @jkim10 Small notes:
> 
> 1. What does the x-axis represent and what is the label hidden behind the $80?
> 2. What do you envision the graph displaying? Does this graph work well when there are more than 10 items? If not, should we consider a [treemap](https://www.d3-graph-gallery.com/treemap.html)?
>    Screen Shot 2020-12-07 at 11 54 37 PM
> 3. For some reason, my new item didn't have a checkout button.
>    Screen Shot 2020-12-07 at 11 55 01 PM

1. Mb did this p last minute last night, but x axis is the time of purchase. the label should say time, but I haven't looked into react-vis styling yet.
2. How would the treemap look? I think the point of the graph would be to show the times where there were a lot of sales, but a treemap would be hard to convey time I think
3. Can you try rescaling the window,  might be a min width thing. If it is, I'll have to rescale the min-width

**Comment by ceguiluzrosas** [comment]
> 1. Mb did this p last minute last night, but x axis is the time of purchase. the label should say time, but I haven't looked into react-vis styling yet.

Gotcha!

> 3. Can you try rescaling the window,  might be a min width thing. If it is, I'll have to rescale the min-width

Yup! That resolved it. I had my Chrome settings as `Font Size: Large`. Switching it to `Medium` fixed it. 

> 2. How would the treemap look? I think the point of the graph would be to show the times where there were a lot of sales, but a treemap would be hard to convey time I think

Here are a couple of potential designs using the date-vs-sale graph and the proportional sale idea I had for the treemap that can also be done with a pie-chart (I completely forgot these existed lol)

Screen Shot 2020-12-08 at 3 49 07 PM
Screen Shot 2020-12-08 at 3 49 15 PM

**Comment by jkim10** [comment]
> @jkim10
> 
> > 1. Mb did this p last minute last night, but x axis is the time of purchase. the label should say time, but I haven't looked into react-vis styling yet.
> 
> Gotcha!
> 
> > 1. Can you try rescaling the window,  might be a min width thing. If it is, I'll have to rescale the min-width
> 
> Yup! That resolved it. I had my Chrome settings as `Font Size: Large`. Switching it to `Medium` fixed it.
> 
> > 1. How would the treemap look? I think the point of the graph would be to show the times where there were a lot of sales, but a treemap would be hard to convey time I think
> 
> Here are a couple of potential designs using the date-vs-sale graph and the proportional sale idea I had for the treemap that can also be done with a pie-chart (I completely forgot these existed lol)
> 
> Screen Shot 2020-12-08 at 3 49 07 PM
> Screen Shot 2020-12-08 at 3 49 15 PM

Pie Chart I think is the easiest for the user. I'll merge this, then work on getting that rendered

**Pull request merged**
