### PR TITLE
Yiqiao/item history

### PR DESCRIPTION
**Pull request by yiqiao-liu**

### CODE REVIEW

**Comment by yiqiao-liu** [comment]
I created an item history page for each store, with route localhost:1234/shop/:shopID/history. However, I continue getting 403 forbidden when I try to edit or create an item in my store. Can someone confirm for me that the item history does show up correctly on that page?

Also, I'm not sure how to read the codecov report. It seems like some files in the backend have their coverage dropped?

@ceguiluzrosas @jkim10 @MattKersey

**Comment by ceguiluzrosas** [comment]
> I created an item history page for each store, with route localhost:1234/shop/:shopID/history. However, I continue getting 403 forbidden when I try to edit or create an item in my store, so I don't have any item history. Can someone confirm for me that the item history does show up correctly on that page?

The item-history shows up for me. Steps to reproduce
- Log into page and click oauth-login 
- Signed in with my credentials: `cee2130@columbia.edu, password`
- Selected store 1
- Selected several items for purchase (got 200s back 😄 )
- Edited details of items (got 403 for PUT/update 😢 )
- Manually entered stor's item-history url: `http://localhost:1234/shop/1/history`
NOTE: The history-records did not show up on the table.

> 
> Also, I'm not sure how to read the codecov report. It seems like some files in the backend have their coverage dropped?
> 

Can you clarify what you mean by "dropped" and which files? @yiqiao-liu

**Comment by yiqiao-liu** [comment]
> > I created an item history page for each store, with route localhost:1234/shop/:shopID/history. However, I continue getting 403 forbidden when I try to edit or create an item in my store, so I don't have any item history. Can someone confirm for me that the item history does show up correctly on that page?
> 
> The item-history shows up for me. Steps to reproduce
> 
> * Log into page and click oauth-login
> * Signed in with my credentials: `cee2130@columbia.edu, password`
> * Selected store 1
> * Selected several items for purchase (got 200s back 😄 )
> * Edited details of items (got 403 for PUT/update 😢 )
> * Manually entered stor's item-history url: `http://localhost:1234/shop/1/history`
>   NOTE: The history-records did not show up on the table.
> 
> > Also, I'm not sure how to read the codecov report. It seems like some files in the backend have their coverage dropped?
> 
> Can you clarify what you mean by "dropped" and which files? @yiqiao-liu

I fixed the history page. The page can at least reflect the purchasing action now. Still not sure about editing and adding because of 403.

For the codecov report, when I saw I could not pass the coverage requirement, I clicked the codecov website. I found the main reason was the coverage of some backend files decreased, but after I merged the main branch to this PR, everything is fine now.

**Comment by ceguiluzrosas** [comment]
> I fixed the history page. The page can at least reflect the purchasing action now. Still not sure about editing and adding because of 403.

The 403 error occurred because of a permission related issue. The create/update endpoints are only permitted for Vendors (and not Managers). The user we both used  (cee2130@columbia.edu)  is a Manager for all their stores and thus the endpoints are inaccessible for that user. Performing the following modifications in the `ItemViewSet` doesn't solve the underlying problem
-  `permission_classes = [TokenHasStoreManagerScope]` : only accessible to manager but not vendors
- `permission_classes = [TokenHasStoreVendorScope]` : only accessible to vendors but not managers
-  `permission_classes = [TokenHasStoreVendorScope, TokenHasStoreManagerScope]` : only accessible to users who are both managers and vendors to that particular store which isn't valid. 

@MattKersey Any idea how we can allow both vendors and managers to use the create/update endpoints?

**Review by ceguiluzrosas — APPROVED** [review]
LGMT 👍🏽

**Pull request merged**
